### ISSUE TITLE
Zoom Area Not Showing

### ISSUE THREAD

**Issue by queejie** [2amigos/egmap#10]
Thanks very much for your effort on this!  I'm wondering if I'm doing something wrong, because the zoom area seems to be corrupted somehow, not showing completely.  I have it in a "plain" view with almost no styles.  It happens whether I show any markers or just simply show the map and do nothing else:

$gMap = new EGMap();
$gMap->zoom = 6;
$gMap->setCenter(42.9, -76);
$gMap->renderMap();

![nysut_pdd_dqj_gmap](https://cloud.githubusercontent.com/assets/1616827/2810479/9204ec52-cdc2-11e3-8955-3a974b6bf240.png)

**Comment by tonydspaniard** [comment]
@queejie That is surely due to some CSS pitfall (don't worry shit happens :)). 

I recommend you to do the following: 
- open Developer Tools (if in Chrome, otherwise Firebug on Firefox)  
- select the element to inspect its CSS  

You will surely find the reason (thats what I did to find mine)

**Comment by queejie** [comment]
Yeah, it was a Bootstrap style, layered pretty deep, on the img tag for the zoom area.  Thanks!
