### ISSUE TITLE
Left panel glitch

### ISSUE THREAD

**Issue by talofo** [2amigos/egmap#12]
![screen shot 2014-05-13 at 19 11 54](https://cloud.githubusercontent.com/assets/292171/2961777/2de2d742-daca-11e3-9830-9eea44a14ca1.png)

When it renders the map, it renders the left panel in a weird way.

**Comment by tonydspaniard** [comment]
Thats a CSS issue... Check you styles... 

It normally happened (to me) when using Bootstrap.

**Comment by talofo** [comment]
Thanks Tony. Actually, I end up finding that, the issue happens when you set your images to max-width:100%. Obviously, the google maps api should be agnostic regardless the developer preferences of their css. Anyway, not an issue on your side. For anyone who may found this, and wish to fix the issue, here's a reference: http://www.yiiframework.com/extension/egmap/#c16208 - Thanks for the brilliant work on this extensions, and so many other contributions to the Yii community. Thanks!
