### ISSUE TITLE
How to open an EGMapInfoWindow by default / on page load?

### ISSUE THREAD

**Issue by Niklas-Peter** [2amigos/egmap#4]
How can I realize this, I could just add
EGMap0_info_window.open(EGMap0,EGMapMarker2);
in the document.ready function, but I want to have a solution, that is built dynamically via PHP, so that I don't have to change anything when variable names changes.

Is there a nice way or more detailed documentation?

**Comment by outOFFspace** [comment]
Join to the question

**Comment by tonydspaniard** [comment]
You will have to recall the name of that info window and append the code on its initialization using its `afterInit` parameters https://github.com/2amigos/egmap/blob/master/EGMap.php#L664

`{NAMEOFYOURINFOWINDOW}.open(map, marker)`
