### ISSUE TITLE
DrawingManager

### ISSUE THREAD

**Issue by Fiorello** [2amigos/egmap#5]
Hi,
i'm using your extension in my project, but i need to use the Drawn tool by Gmap.
I'd like to know if there is a method to use it by your extension, or if i have to use classic google code.
Thanks

**Comment by tonydspaniard** [comment]
@Fiorello Drawing Manager was included lately and currently EGmap doesn't support it in its core. You will have to append the parameter to the URL your self and then initialize it on its `appendJs`
