### ISSUE TITLE
EGMap inside form element (CActiveForm) breaks yiiactiveform js

### ISSUE THREAD

**Issue by Jaredmmx** [2amigos/egmap#9]
I placed an EGMap inside a CActiveForm with ClientValidation and AjaxValidation, but when the page loads console says 'Uncaught TypeError: undefined is not a function ' in the line where yiiactiveform is assigned the form id and the validation rules.

with Firefox, error is 'TypeError: jQuery(...).yiiactiveform is not a function'

If I remove the EGMAP (v.2, just dowloaded form github by the way), form is working properly.

jquery.yiiactiveform.js is loaded, anyway. It just doesn't work

**Comment by tonydspaniard** [comment]
Thats very strange... mind sharing some code @Jaredmmx ?

**Comment by Jaredmmx** [comment]
Yes it was an strange behaviour, but I finallly realized it wasn't because
of EGMap, but because of a renderPartial that broke everything only when
EGMap was in the form (I made a plugin to use de EGMap).

Thank you anyway for your interest, your doubts made me test further.

Great job!.

2014-04-19 18:17 GMT+01:00 Antonio Ramirez notifications@github.com:

**Comment by tonydspaniard** [comment]
@Jaredmmx good to know!
